#!/bin/bash

# Fix SSH auth socket location so agent forwarding works with screen.
if [ -e "$SSH_AUTH_SOCK" ] ; then
    ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
    # export SSH_AUTH_SOCK=$HOME/.ssh/ssh_auth_sock
fi

# Need to run xauth since this file exists. Check sshd(8) manpage for details.
if read proto cookie && [ -n "$DISPLAY" ]; then
        if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
                # X11UseLocalhost=yes
                echo add unix:`echo $DISPLAY |
                    cut -c11-` $proto $cookie
        else
                # X11UseLocalhost=no
                echo add $DISPLAY $proto $cookie
        fi | xauth -q -
fi
