#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# Repo URL
# git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
#
# Extra plugins to go in `~/.zprezto/modules`
# git clone https://github.com/psprint/zsh-navigation-tools.git
# git clone https://github.com/hlissner/zsh-autopair.git

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# alias vim="nvim"
alias catn="cat -n"
alias cd..="cd .."
alias duall="du -shc .[!.]* *"
alias gita="git add"
alias gitc="git commit"
alias gitd="git diff"
alias gitds="git diff --staged"
alias gitl="git log -1"
alias gitrso="git remote show origin"
alias gits="git status"
alias gt='cd $(git rev-parse --show-toplevel 2>/dev/null || (echo "."; echo "Not within a git repository" >&2))'
alias ll="ls -AlhF"
alias psgrep='ps aux | grep -v grep | grep'
alias sl="ls"
alias tmat="tmux attach"
alias tmgn="tmux new-session -s general"
alias tmnw="tmux new-session -s"
alias tmux="tmux -2"
alias vimo="vim -O"
alias vimp="vim -p"
# alias vimdiff="vim -d"
# Neovim Remote Activation
if [ -n "${NVIM_LISTEN_ADDRESS}" ]; then
  alias vims='nvr -o'
  alias vimv='nvr -O'
  alias vimt='nvr --remote-tab'
fi
export PATH="$PATH:$HOME/.local/bin"

# keybindings for history-substring-search
# bind P and N for EMACS mode
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down
# bind k and j for VI mode
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# keybindings for zsh-navigation-tools
zle -N znt-cd-widget
bindkey '^[w' znt-cd-widget
znt_cd_hotlist=(
    ~/devbench
    ~/.files
    ~/downloads
    ~/.config/znt
)

# accept and execute the current suggestion with ctrl+space
bindkey '^ ' autosuggest-execute
