#!/bin/bash

echoerr() { echo "$@" 1>&2; }

# Fix SSH auth socket location so agent forwarding works with screen.
if [ -e "$SSH_AUTH_SOCK" ] ; then
    ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
else
    echoerr "ssh-agent has not been initiated.\nRun\n  $~> eval \$\(ssh-agent\)\n  $~> ssh-add\nThen either start tmux or attach to a session and source your tmux conf\nif tmux is already running."
fi

# Need to run xauth since this file exists. Check sshd(8) manpage for details.
if read proto cookie && [ -n "$DISPLAY" ]; then
        if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
                # X11UseLocalhost=yes
                echo add unix:`echo $DISPLAY |
                    cut -c11-` $proto $cookie
        else
                # X11UseLocalhost=no
                echo add $DISPLAY $proto $cookie
        fi | xauth -q -
fi
