#! /bin/bash

. lemonpanel.config

if [ $(pgrep -cx $(basename $0)) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

bspc config -m "$(xrandr | grep LVDS1 | cut -d' ' -f1)" top_padding $PANEL_HEIGHT

admiral | \
    lemonbar -d \
    -n "$PANEL_WM_NAME" \
    -g "$BAR_GEOMETRY" \
    -o "$FONT1_OFFSET" -f "$FONT1" -o "$FONT2_OFFSET" -f "$FONT2" \
    -F "$BAR_FG" -B "$BAR_BG" -U "$BAR_UL" \
    -a 30 -u 5 \
    | zsh &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$PANEL_WM_NAME")
	tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
