#! /bin/bash

sxhkd &

bspc config border_width         4
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true
bspc config pointer_modifier     mod4
bspc config external_rules_command ~/.files/etc/bspwm_config/bin/bspwm_external_rules.sh

bspc monitor LVDS1 -d          
bspc monitor HDMI1 -d 

bspc config normal_border_color '#1b1b1b'
bspc config active_border_color '#193751'
bspc config focused_border_color '#2b5c88'

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mpv state=floating
bspc rule -a lxappearance state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Xfce4-terminal state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Florence state=floating sticky=on
bspc rule -a Spotify desktop=^10
bspc rule -a "Tor Browser":Places state=floating
# bspc rule -a Spacefm:Stopped state=floating
bspc rule -a D-feet state=floating
bspc rule -a Blueman-manager state=floating

# additions
sh ~/.fehbg &
xsetroot -cursor_name left_ptr &
run_modmaps &
compton --vsync opengl &
admiral_panel &
clipit -d -n &
libinput-gestures-setup start &
conky &
