#! /bin/bash

sxhkd &

bspc config border_width         4
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

# bspc monitor LVDS1 -d $(echo -e '\uf120') $(echo -e '\uf269') \
#     $(echo -e '\uf17c') $(echo -e '\uf013') $(echo -e '\uf109') \
#     $(echo -e '\uf2dc') $(echo -e '\uf085') $(echo -e '\uf197') \
#     $(echo -e '\uf0ad')
# bspc monitor HDMI1 -d $(echo -e '\uf26c')
bspc monitor LVDS1 -d         

bspc config focused_border_color '#1b1b1b'

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mpv state=floating
bspc rule -a lxappearance state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Xfce4-terminal state=floating
bspc rule -a Blueman-manager state=floating

# additions
sh ~/.fehbg &
xsetroot -cursor_name left_ptr &
run_modmaps &
compton --vsync opengl &
admiral_panel &
clipit -d -n &
libinput-gestures-setup start &
conky &
